version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # This mounts the root of your project to /app inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
